name: budget-prime

services:
  pg:
    image: postgres:18
    restart: always

    environment:
       POSTGRES_USER: docker
       POSTGRES_PASSWORD: docker
       POSTGRES_DB: budget_prime

    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: